service: dynamocount
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: x86_64
  memorySize: 128
  timeout: 10
  httpApi:
    payload: "2.0"
    authorizers:
      APIAUTH:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - Ref: UserPoolClient
  environment:
    COUNTER_TABLE: 
      Ref: dataTable
    GROUP_TABLE: 
      Ref: dataTable
    USER_TABLE: 
      Ref: dataTable
    PERMISSION_TABLE: 
      Ref: permissionTable
    USER_POOL:
      Ref: UserPool
    USER_POOL_CLIENT:
      Ref: UserPoolClient
    USER_EMAIL_LOOKUP: emailLookup
  iam:
    role:
      name:  counterTableRWAccess
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:Scan'
            - 'dynamodb:Query'
            - 'dynamodb:DeleteItem'
          Resource: 
            - !GetAtt permissionTable.Arn
            - !GetAtt dataTable.Arn
            - Fn::Join:
              - 
              - - !GetAtt dataTable.Arn
                - /index/emailLookup
        - Effect: Allow
          Action:
            - 'cognito-idp:AdminCreateUser'
            - 'cognito-idp:AdminInitiateAuth'
            - 'cognito-idp:AdminSetUserPassword'
          Resource: !GetAtt UserPool.Arn


package:
  patterns:
    - '!*'
    - 'bootstrap'

## include auto-generated 'functions' block
functions:
  - ${file(serverless/sls_api_handlers.yaml)}

resources:
  Resources:
    permissionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userUUID
            AttributeType: S
          - AttributeName: objectTypeUUID
            AttributeType: S
        KeySchema:
          - AttributeName: userUUID
            KeyType:  HASH
          - AttributeName: objectTypeUUID
            KeyType:  RANGE    
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1

    dataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: objectUUID
            AttributeType: S
          - AttributeName: objectType
            AttributeType: S
          - AttributeName: userEmail
            AttributeType: S
        KeySchema:
          - AttributeName: objectUUID
            KeyType:  HASH
          - AttributeName: objectType
            KeyType:  RANGE     
        GlobalSecondaryIndexes:
          - IndexName: emailLookup
            KeySchema:
              - AttributeName: userEmail
                KeyType:  HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true           
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"

    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId: 
          Ref: UserPool
        Domain: 
          Fn::Join:
            - '-'
            - - Ref: HttpApi
              - Ref: UserPoolClient
