service: dynamocount
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: x86_64
  memorySize: 128
  timeout: 10
  httpApi:
    payload: "1.0"

  environment:
    COUNTER_TABLE: 
      Ref: counterTable
  iam:
    role:
      name:  counterTableRWAccess
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:GetItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:Scan'
            - 'dynamodb:DeleteItem'
          Resource:
            Fn::Join:	
              - ''
              - - 'arn:aws:dynamodb:*:*:table/'
                - Ref: counterTable



package:
  patterns:
    - '!*'
    - 'bootstrap'

functions:
  apiv1:
    handler: apiv1
    events:
      - httpApi:
          method: '*'
          path: /api/v1/{Path+}


resources:
  Resources:
    counterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: counterName
            AttributeType: S
        KeySchema:
          - AttributeName: counterName
            KeyType:  HASH     
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


